### ISSUE TITLE
想问一下SGN的问题

### ISSUE THREAD

**Issue by guoliwu** [MarcusNerva/detail-captioning#1]
不好意思，打扰了，我看到你在Senmantic Grouping Network for Video Captioning 提问，所以想问一下你的按照官方他提供的代码，MSR-VTT数据集的CIDEr达到49.5了吗

**Comment by MarcusNerva** [comment]
@guoliwu 我后来没跑那段代码了。

不过有一点我要说明一下，那篇文章在进行caption 预处理的时候犯了严重错误。原理上来说，我们把模型放在test dataset上测试时，test dataset的ground-truth caption不应该有任何改动，最多就是把字母大写转成小写。而他不仅移除了ground-truth caption 中的标点符号，而且竟然还对ground-truth caption进行了裁剪。裁剪后ground-truth 变短，那么最后的结果自然就会偏高。

以下结合代码说明：
https://github.com/hobincar/SGN/blob/df5dff4eaf5f957826e374fd510383849451d348/utils.py#L198
![image](https://user-images.githubusercontent.com/37070207/136878772-c6e07c47-1a59-4991-9f8c-aaaf84c3b4a4.png)

https://github.com/hobincar/SGN/blob/df5dff4eaf5f957826e374fd510383849451d348/train.py#L49
![image](https://user-images.githubusercontent.com/37070207/136879533-0124b9fc-e9ed-493b-a900-bfe8ab841bc9.png)

https://github.com/hobincar/SGN/blob/df5dff4eaf5f957826e374fd510383849451d348/loader/data_loader.py#L279
![image](https://user-images.githubusercontent.com/37070207/136879706-4db3ad5f-c222-4da2-9c1b-76c79d06aabb.png)

https://github.com/hobincar/SGN/blob/df5dff4eaf5f957826e374fd510383849451d348/loader/data_loader.py#L174
![image](https://user-images.githubusercontent.com/37070207/136879869-4a04b434-3214-40db-8a7e-370cf1a2759a.png)

**Comment by guoliwu** [comment]
非常感谢你的回复，我自在复现的过程中无论如何都达不到论文里的指标，只能达到48.8，和论文里的49.5还差的很远，所以非常疑惑。非常感谢你的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MarcusNerva/detail-captioning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月12日(星期二) 上午10:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MarcusNerva/detail-captioning] 想问一下SGN的问题 (#1)





 
我后来没跑那段代码了。
 
不过有一点我要说明一下，那篇文章在进行caption 预处理的时候犯了严重错误。原理上来说，我们把模型放在test dataset上测试时，test dataset的ground-truth caption不应该有任何改动，最多就是把字母大写转成小写。而他不仅移除了ground-truth caption 中的标点符号，而且竟然还对ground-truth caption进行了裁剪。裁剪后ground-truth 变短，那么最后的结果自然就会偏高。
 
以下结合代码说明：
 https://github.com/hobincar/SGN/blob/df5dff4eaf5f957826e374fd510383849451d348/utils.py#L198
 
 
https://github.com/hobincar/SGN/blob/df5dff4eaf5f957826e374fd510383849451d348/train.py#L49
 
 
https://github.com/hobincar/SGN/blob/df5dff4eaf5f957826e374fd510383849451d348/loader/data_loader.py#L279
 
 
https://github.com/hobincar/SGN/blob/df5dff4eaf5f957826e374fd510383849451d348/loader/data_loader.py#L174
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
